(add-to-list 'auto-mode-alist '("\\.h\\'" . c++-mode))
(setq make-backup-files nil)
(setq truncate-partial-width-windows nil)
(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)
(setq column-number-mode t)
(setq indent-line-function 'insert-tab)
(setq c-default-style "stroustrup")
(setq c-basic-offset 4)
(setq scroll-conservatively most-positive-fixnum)
(setq ido-enable-flex-matching t)
;;(setq ido-everywhere t)
(setq transient-mark-mode t)
(setq electric-indent-mode nil)
(ido-mode 1)
(defalias 'list-buffers 'ibuffer)

(global-set-key [f12] 'eval-buffer)
(global-set-key [f8] 'goto-line)
(global-set-key [?\C-r] 'replace-string)
(global-set-key [?\C-z] 'undo)
(global-set-key [?\C-0] 'delete-window)
(global-set-key [?\C-1] 'delete-other-windows)
(global-set-key [?\C-2] 'split-window-vertically)
(global-set-key [?\C-3] 'split-window-horizontally)
(global-set-key [C-return] 'save-buffer)

(define-key global-map [C-right] 'forward-word)
(define-key global-map [C-left] 'backward-word)
(define-key global-map [C-up] 'previous-blank-line)
(define-key global-map [C-down] 'next-blank-line)
(define-key global-map [home] 'beginning-of-line)
(define-key global-map [end] 'end-of-line)
(define-key global-map [pgup] 'forward-page)
(define-key global-map [pgdown] 'backward-page)
(define-key global-map [C-next] 'scroll-other-window)
(define-key global-map [C-prior] 'scroll-other-window-down)

(desktop-save-mode 1)
(delete-selection-mode 1)
(global-auto-revert-mode 1)
(tool-bar-mode -1)


(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:foreground "#000000" :background "#ffffea"))))
 '(highlight ((t (:foreground "##ffffea" :background "#eeee9e"))))
 '(mode-line ((t (:inverse-video t))))
 '(region ((t (:background "#eeee9e"))))

 '(c-tab-always-indent t)
 '(column-number-mode t)
 '(custom-enabled-themes nil)
 '(display-line-numbers t)
 '(safe-local-variable-values '((c-offsets-alist)))
 '(tab-bar-mode t)
 '(tab-bar-show nil)
 '(tool-bar-mode nil)
 '(truncate-lines t))

(global-font-lock-mode 1)

(set-background-color "#ffffea")
;;(add-to-list 'default-frame-alist '(font . "Liberation Mono-11.5"))
;;(set-face-attribute 'default t :font "Liberation Mono-11.5")
;;(add-to-list 'default-frame-alist '(font . "Consolas-11"))
;;(set-face-attribute 'default t :font "Consolas-11")
(add-to-list 'default-frame-alist '(font . "Cascadia Mono-10"))
(set-face-attribute 'default t :font "Cascadia Mono-10")
